#!/bin/bash
set -e

VERSION=1.0

PROMPT="dmenu:"
IGNORE_CASE="nil"

escape() {
    echo "${1//\"/\\\"}"
}

while getopts ":ip:" opt; do
    case $opt in
        p) PROMPT="$OPTARG " ;;
        i) IGNORE_CASE="t" ;;
        v)
            echo "emacs-based dmenu replacement: ${VERSION}"
            exit 0
            ;;
        ;;
        \?) ;; # IGNORE
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))

cleanup() {
    trap - TERM INT EXIT
    if [[ -O "$FILE" ]]; then
        rm -f "$FILE" || :
    fi
}
trap "cleanup" TERM INT EXIT

FILE=$(mktemp)
PROGRAM='
(let ((file-name "'$(escape "$FILE")'")
      (completion-ignore-case '$IGNORE_CASE')
      (prompt "'$(escape "$PROMPT")'"))
  (with-temp-buffer
    (insert-file-contents file-name)
    (let* ((contents (delete-and-extract-region (point-min) (point-max)))
           (options (split-string contents "\n" t))
           (choice (call-interactively
             (lambda (choice)
               (interactive (list (completing-read prompt options)))
               choice))))
      (insert choice)
      (insert "\n"))
    (write-region nil nil file-name nil 0)))
'

cat > "$FILE"

if emacsclient -n --eval "$PROGRAM" >/dev/null 2>&1; then
    cat "$FILE"
    exit 0
else
    exit 1
fi
