#!/bin/bash
set -e

PROMPT="dmenu:"

escape() {
    echo "${1//\"/\\\"}"
}

while getopts "p:" opt; do
    case $opt in
        p) PROMPT="$OPTARG" ;;
        \?) ;; # IGNORE
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))

cleanup() {
    trap - TERM INT EXIT
    if [[ -O "$FILE" ]]; then
        rm -f "$FILE" || :
    fi
}
trap "cleanup" TERM INT EXIT

FILE=$(mktemp)
PROGRAM='(with-temp-buffer
  (insert-file-contents "'$(escape "$FILE")'")
  (completing-read "'$(escape "$PROMPT")'" (split-string (buffer-string) "\n" t)))'

cat > "$FILE"

OUTPUT="$(emacsclient -n --eval "$PROGRAM")"

if [[ "$OUTPUT" =~ ^\"(.*)\"$ ]]; then
    eval "echo $'${BASH_REMATCH[1]}'"
    exit 0
else
    exit 1
fi
